name: Release

on:
  workflow_dispatch

#env:
#  LIB_VERSION: 0.0.0.0 # experimental version

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        clean: 'true'
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle clean
      run: ./gradlew clean --info
    - name: Build with Gradle
      run: ./gradlew -Pversion=$LIB_VERSION build --info
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-jvm-${{ steps.gitversion.outputs.SemVer }}.jar
        asset_name: GrowthBook-$LIB_VERSION.jar
        asset_content_type: application/x-jar
    - name: Upload sources
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-kotlin-$LIB_VERSION-sources.jar
        asset_name: GrowthBook-kotlin-${{ steps.gitversion.outputs.SemVer }}-sources.jar
        asset_content_type: application/x-jar
    - name: Upload metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GrowthBook/build/libs/GrowthBook-metadata-$LIB_VERSION.jar
        asset_name: GrowthBook-metadata-$LIB_VERSION-all.jar
        asset_content_type: application/x-jar
